anima-wg/brski-cloud

- .travis.yml
- Makefile
- anima-brski-cloud.md
- ietf-redirected-voucher.yang
- insert-figures
this added the YANG machinery and a basic extension to RFC8366 to add the est-domain attribute.
> wrote YANG module, include it into the text using insert-figures

- anima-brski-cloud.md
This includes Rifaat's changes from https://docs.google.com/document/d/1L_OpM4wUfQQdBlDzc1SLeLtiwS8iWCDBpl6nmmO-6zE/edit
> Explain the Cloud-handled Voucher-Request

- anima-brski-cloud.md
- ietf-voucher-redirected.yang
security considerations written based upon discussion and notes
> security considerations for differing redirect processing

- anima-brski-cloud.md
> brian-carpenter-section-1-nits

- anima-brski-cloud.md
> brian-carpenter-architecture

- anima-brski-cloud.md
> brian-carpenter-network-connectivity

- anima-brski-cloud.md
> brian-carpenter-section-3-nits

- anima-brski-cloud.md
> brian-carpenter-introduction

- anima-brski-cloud.md
> brian-carpenter-abstract

- anima-brski-cloud.md
> Introduction bc comments

- anima-brski-cloud.md
close #43 
close #44 
close #45 
close #46 
close #42
> ESKO editorial nits

- anima-brski-cloud.md
close #51 
we never use this term
> Remove local domain registrar

- anima-brski-cloud.md
Addresses:
#55 
#56 
and partially:
#58
> Toreless - Update Architecture

- anima-brski-cloud.md
> Toreless - draft-5 section 1.2.1: Nits

- anima-brski-cloud.md
> Toreless - draft-5 section 1.2.2: EST server deploy nit

- anima-brski-cloud.md
> Toreless - draft-5 section 1.2.2: Rename to Cloud Registrar and Owner EST-Server

- anima-brski-cloud.md
> Toreless - draft-5 section 4.1: Cloud RA terminology

- anima-brski-cloud.md
> Toreless - draft-5 section 2.3: clarify which registrar is used

- anima-brski-cloud.md
> Toreless - draft-5 section 2.2: assumptions about Network Connectivity

- anima-brski-cloud.md
> Toreless - draft-5 section 2.3: clarify contents of CSR request

- anima-brski-cloud.md
> Toreless remove OEM term

- anima-brski-cloud.md
> Toreless - draft-5 section 4.2: validation vs authentication of EST server

- anima-brski-cloud.md
> AD review 03: nit level comments

- anima-brski-cloud.md
> Toreless - draft-5 section 3.2.2: clarify how/when owner registrar registers to cloud registrar

- anima-brski-cloud.md
> Toreless - draft-5 section 1.2: fixes to Target Use Cases

- anima-brski-cloud.md
> toreless-abstract

- anima-brski-cloud.md
> Toreless - draft-5 section 3.3.1: onboarding vs bootstrapping vs enrollment

- anima-brski-cloud.md
> fixed mis-typed reference

- anima-brski-cloud.md
close #83
close #84
close #87
close #110
> Toreless redirect security and VAR

- anima-brski-cloud.md
> toreless-voucher-response

- anima-brski-cloud.md
> toreless-unknown-pledges

- anima-brski-cloud.md
> toreless-introduction-text

- anima-brski-cloud.md
> remove-network-integrator

- anima-brski-cloud.md
> Toreless- SNI comments

- anima-brski-cloud.md
> toreless - well-known-uri

- anima-brski-cloud.md
> toreless-and-AD-redirect-response

- anima-brski-cloud.md
> rpk-and-self-signed=cert

- anima-brski-cloud.md
> core-argument-concerns

- anima-brski-cloud.md
> mahesh-provisional-tls

- anima-brski-cloud.md
> mahesh-clarify-registrar

- anima-brski-cloud.md
> add new section on lifecycle considerations

- anima-brski-cloud.md
> document when to insert Retry-After

- anima-brski-cloud.md
> Redirects vs failures

- anima-brski-cloud.md
> Pledge not pledge

- anima-brski-cloud.md
https://mailarchive.ietf.org/arch/msg/iot-directorate/nynYw4VaBb3nvkLe3INt68zOA5I/
> Qin iotdir comments

- anima-brski-cloud.md
> remove repeative text

- anima-brski-cloud.md
> rewrite DoS at TLS connection time considerations

- anima-brski-cloud.md
to explicitely mention that owner registrars are EST servers
close #203
> change redirect to registrar diagram

- anima-brski-cloud.md
> start new paragraph, explain voucher connection better

- anima-brski-cloud.md
close #207.
We do not agree that the introduction and Use case section are repetitive.
> update terminology, expand VAR term

- anima-brski-cloud.md
> Issue 184 (part 1)

- anima-brski-cloud.md
> move sentence down, include mention of CSR attributes

- anima-brski-cloud.md
> use better captive portal text

- anima-brski-cloud.md
> converted many may->MAY

- anima-brski-cloud.md
> add note about lifecycle management of EST server certificate

- anima-brski-cloud.md
> Trust anchor security considerations

- anima-brski-cloud.md
> Issue 184 and 206

- anima-brski-cloud.md
> dnsdir-review

- anima-brski-cloud.md
> rfc8366bis

- anima-brski-cloud.md
> rework paragraph explaining what the existing DHCP options are

- anima-brski-cloud.md
> rewrite redirect explanation for when companies die or merge

- anima-brski-cloud.md
> explain VR-sign in arch-one

- anima-brski-cloud.md
be more explicit about updating 8995.
> add very very explicit updates 8995

- anima-brski-cloud.md
> deb-trust-anchors

- anima-brski-cloud.md
> Eric Vyncke missed comments
